const mongoose = require("mongoose");

const fileSchema = new mongoose.Schema(
  {
    path: { type: String },
    originalName: { type: String },
    mimeType: { type: String },
    size: { type: Number },
  },
  { _id: false }
);

const applicationSchema = new mongoose.Schema(
  {
    collegeSlug: { type: String },
    status: {
      type: String,
      enum: ["pending", "reviewing", "approved", "rejected"],
      default: "pending",
    },
    registration: {
      formName: String,
      registeredName: String,
      registeredEmail: String,
      registrationDate: Date,
      registeredMobile: String,
      registeredCountry: String,
      alternateMobile: String,
      alternateMobileNo: String,
      state: String,
      city: String,
      course: String,
      admissionIntake: String,
      occupation: String,
      relationship: String,
      annualIncome: String,
      fatherName: String,
      applicationNo: String,
      program: String,
      specialization: String,
      schoolName: String,
      categoryNationality: String,
      admissionOwner: String,
      admissionCategory: String,
      withdrawalDocsEligible: String,
      title: String,
      referralCode: String,
    },
    applicant: {
      title: String,
      firstName: String,
      middleName: String,
      lastName: String,
      email: String,
      mobile: String,
      dateOfBirth: Date,
      gender: String,
      placeOfBirth: String,
      religion: String,
      bloodGroup: String,
      maritalStatus: String,
      requireTransport: String,
      requireHostel: String,
      roomType: String,
      pwd: String,
      casteCategory: String,
      aadharNumber: String,
      applicable: String,
      countryOfBirth: String,
      visaType: String,
      visaNumber: String,
      visaDuration: String,
      fee: String,
      countryOfResidence: String,
      passportNumber: String,
      passportCountry: String,
      passportPlaceOfIssue: String,
      passportDateOfIssue: Date,
      passportDateOfExpiry: Date,
    },
    parents: {
      father: {
        name: String,
        email: String,
        mobile: String,
        pan: String,
        occupation: String,
        designation: String,
      },
      mother: {
        name: String,
        email: String,
        mobile: String,
        pan: String,
        occupation: String,
        designation: String,
      },
      guardian: {
        name: String,
        email: String,
        mobile: String,
        pan: String,
        occupation: String,
        designation: String,
      },
    },
    addresses: {
      communication: {
        country: String,
        state: String,
        district: String,
        city: String,
        addressLine1: String,
        addressLine2: String,
        pincode: String,
      },
      permanent: {
        country: String,
        state: String,
        district: String,
        city: String,
        addressLine1: String,
        addressLine2: String,
        pincode: String,
      },
      permanentSameAsCommunication: { type: Boolean, default: false },
    },
    education: {
      tenth: {
        instituteName: String,
        board: String,
        rollNo: String,
        yearOfPassing: String,
        percentage: String,
        markingScheme: String,
        studiedKannada: String,
        studiedUpTo10th: String,
        studiedUpTo12th: String,
        after10thQualification: String,
      },
      twelfth: {
        instituteNameWithBranch: String,
        board: String,
        rollNo: String,
        stream: String,
        yearOfPassing: String,
        resultStatus: String,
        percentage: String,
        subjects: [
          {
            subject: String,
            maxMarks: String,
            obtainedMarks: String,
            percentage: String,
          },
        ],
        totals: {
          totalSubjects: String,
          totalMaxMarks: String,
          totalObtainedMarks: String,
          totalPercentage: String,
        },
      },
      diploma: {
        instituteNameWithBranch: String,
        boardOrUniversity: String,
        rollNo: String,
        stream: String,
        yearOfPassing: String,
        resultStatus: String,
        percentage: String,
      },
      ug: {
        resultStatus: String,
        institute: String,
        university: String,
        registerNumber: String,
        yearOfPassing: String,
        totalMarks: String,
        marksObtained: String,
        overallPercentage: String,
        subjects: [
          {
            subject: String,
            maxMarks: String,
            obtainedMarks: String,
            percentageOrGrade: String,
          },
        ],
        totals: {
          totalSubjects: String,
          totalMaxMarks: String,
          totalObtainedMarks: String,
          totalPercentage: String,
        },
      },
      others: {
        instituteName: String,
        university: String,
        degree: String,
        yearOfPassing: String,
        resultStatus: String,
        percentage: String,
      },
      international: {
        oLevel: {
          instituteName: String,
          board: String,
          certificateName: String,
          yearOfPassing: String,
          marksScore: String,
          gpaGradePercentage: String,
        },
        aLevel: {
          instituteName: String,
          board: String,
          certificateName: String,
          yearOfPassing: String,
          marksScore: String,
          gpaGradePercentage: String,
        },
        diplomaCertificate: {
          instituteName: String,
          board: String,
          certificateName: String,
          yearOfPassing: String,
          marksScore: String,
          gpaGradePercentage: String,
        },
        bachelors: {
          instituteName: String,
          board: String,
          certificateName: String,
          yearOfPassing: String,
          marksScore: String,
          gpaGradePercentage: String,
        },
        masters: {
          instituteName: String,
          board: String,
          certificateName: String,
          yearOfPassing: String,
          marksScore: String,
          gpaGradePercentage: String,
        },
        otherQualification: {
          instituteName: String,
          board: String,
          certificateName: String,
          yearOfPassing: String,
          marksScore: String,
          gpaGradePercentage: String,
        },
      },
      entranceExams: {
        appeared: String,
        exams: [
          {
            name: String,
            rollNo: String,
            year: String,
            resultStatus: String,
            score: String,
            rank: String,
          },
        ],
      },
    },
    uploads: {
      photo: fileSchema,
      signature: fileSchema,
      diplomaCertificate: fileSchema,
      bachelorCertificate: fileSchema,
      masterCertificate: fileSchema,
      otherQualificationCertificate: fileSchema,
    },
    declaration: {
      applicantName: String,
      parentName: String,
      date: Date,
    },
  },
  { timestamps: true }
);

const Application = mongoose.model("Application", applicationSchema);

module.exports = Application;
